<Project Sdk="Azure.Functions.Sdk/1.0.0">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />

    <PackageReference Include="AutoMapper" />

    <PackageReference Include="Microsoft.Azure.Functions.Worker" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.OpenTelemetry" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" />

    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="Azure.Monitor.OpenTelemetry.Exporter" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SupportAssistant.Application\SupportAssistant.Application.csproj" />
    <ProjectReference Include="..\SupportAssistant.Infrastructure\SupportAssistant.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\.dockerignore">
      <Link>.dockerignore</Link>
    </Content>
  </ItemGroup>

</Project>